export const cards = [
  {
    id: 0,
    name: "Jester",
    strength: 0,
    countNormal: 0,
    countPremium: 1,
    effect: "Choose a player. If they win, you gain a token.",
  },
  {
    id: 1,
    name: "Guard",
    strength: 1,
    countNormal: 5,
    countPremium: 8,
    effect: "Guess a strength (≠1). If correct, target is eliminated.",
  },
  {
    id: 2,
    name: "Priest",
    strength: 2,
    countNormal: 2,
    countPremium: 2,
    effect: "View another player's hand.",
  },
  {
    id: 3,
    name: "Baron",
    strength: 3,
    countNormal: 2,
    countPremium: 2,
    effect: "Compare hands. Lower card is eliminated.",
  },
  {
    id: 4,
    name: "Handmaid",
    strength: 4,
    countNormal: 2,
    countPremium: 2,
    effect: "You are protected until your next turn.",
  },
  {
    id: 5,
    name: "Prince",
    strength: 5,
    countNormal: 2,
    countPremium: 2,
    effect: "Target discards hand and draws a new one.",
  },
  {
    id: 6,
    name: "King",
    strength: 6,
    countNormal: 1,
    countPremium: 1,
    effect: "Trade hands with another player.",
  },
  {
    id: 7,
    name: "Countess",
    strength: 7,
    countNormal: 1,
    countPremium: 1,
    effect: "Must be played if with Prince or King.",
  },
  {
    id: 8,
    name: "Princess",
    strength: 8,
    countNormal: 1,
    countPremium: 1,
    effect: "If discarded, you are eliminated.",
  },
  {
    id: 9,
    name: "Bishop",
    strength: 9,
    countNormal: 0,
    countPremium: 1,
    effect: "Guess a strength. If correct, gain an affection token.",
  },
  {
    id: 10,
    name: "Constable",
    strength: 6,
    countNormal: 0,
    countPremium: 1,
    effect: "If eliminated, gain 1 affection token.",
  },
  {
    id: 11,
    name: "Dowager Queen",
    strength: 7,
    countNormal: 0,
    countPremium: 1,
    effect: "Compare hands. Higher is eliminated.",
  },
  {
    id: 12,
    name: "Sycophant",
    strength: 4,
    countNormal: 0,
    countPremium: 2,
    effect: "Choose who the next player must target.",
  },
  {
    id: 13,
    name: "Cardinal",
    strength: 2,
    countNormal: 0,
    countPremium: 2,
    effect: "Trade hands. View the new card if you wish.",
  },
  {
    id: 14,
    name: "Assassin",
    strength: 0,
    countNormal: 0,
    countPremium: 1,
    effect: "If targeted with Guard, eliminate attacker instead.",
  },

  {
    id: 15,
    name: "Baroness",
    strength: 3,
    countNormal: 0,
    countPremium: 2,
    effect: "View the hands of two players.",
  },
  {
    id: 16,
    name: "Count",
    strength: 5,
    countNormal: 0,
    countPremium: 2,
    effect: "If discarded or played, add +1 to your hand strength.",
  },
];
