export const cards = [
  {
    name: "Guard",
    strength: 1,
    countNormal: 5,
    countPremium: 8,
    effect:
      "Choose another player and name a strength number (≠ 1). If correct, they are eliminated.",
  },
  {
    name: "Priest",
    strength: 2,
    countNormal: 2,
    countPremium: 2,
    effect: "Privately view another player's hand.",
  },
  {
    name: "Cardinal",
    strength: 2,
    countNormal: 0,
    countPremium: 2,
    effect: "Trade hands with another player. You may look at their new card.",
  },
  {
    name: "Baron",
    strength: 3,
    countNormal: 2,
    countPremium: 2,
    effect: "Privately compare hands. The lower card is eliminated.",
  },
  {
    name: "Baroness",
    strength: 3,
    countNormal: 0,
    countPremium: 2,
    effect: "Privately view two players' hands.",
  },
  {
    name: "Handmaid",
    strength: 4,
    countNormal: 2,
    countPremium: 2,
    effect: "You cannot be targeted until your next turn.",
  },
  {
    name: "Sycophant",
    strength: 4,
    countNormal: 0,
    countPremium: 2,
    effect: "Choose a player to be the target of the next effect card played.",
  },
  {
    name: "Prince",
    strength: 5,
    countNormal: 2,
    countPremium: 2,
    effect: "Choose a player to discard and draw a new card.",
  },
  {
    name: "Count",
    strength: 5,
    countNormal: 0,
    countPremium: 2,
    effect:
      "If discarded or played and still in the round, your card strength increases by 1.",
  },
  {
    name: "Constable",
    strength: 6,
    countNormal: 0,
    countPremium: 1,
    effect: "If eliminated by any means, gain 1 affection token.",
  },
  {
    name: "King",
    strength: 6,
    countNormal: 1,
    countPremium: 1,
    effect: "Trade hands with another player.",
  },
  {
    name: "Countess",
    strength: 7,
    countNormal: 1,
    countPremium: 1,
    effect: "Must be played if with Prince or King. Does nothing otherwise.",
  },
  {
    name: "Dowager Queen",
    strength: 7,
    countNormal: 0,
    countPremium: 1,
    effect: "Compare hands. Higher value is eliminated.",
  },
  {
    name: "Princess",
    strength: 8,
    countNormal: 1,
    countPremium: 1,
    effect: "If played or discarded, you are eliminated.",
  },
  {
    name: "Bishop",
    strength: 9,
    countNormal: 0,
    countPremium: 1,
    effect:
      "Guess another player's card strength. If correct, gain an affection token.",
  },
  {
    name: "Jester",
    strength: 0,
    countNormal: 0,
    countPremium: 1,
    effect:
      "Give the token to a player. If they win the round, you gain 1 affection token.",
  },
  {
    name: "Assassin",
    strength: 0,
    countNormal: 0,
    countPremium: 1,
    effect: "If targeted, reveal to eliminate the attacker instead.",
  },
];
