// Helper function to get the correct card image
export const getCardImage = (cardName) => {
  const imageMap = {
    Jester: "jester1.jpeg",
    Guard: "guard1.jpeg",
    Priest: "priest1.jpeg",
    Baron: "baron1.jpeg",
    Handmaid: "handmaid1.jpeg",
    Prince: "prince1.jpeg",
    "Phantom King": "phantom-king1.jpeg",
    Countess: "countess1.jpeg",
    Princess: "princess-portrait1.jpeg",
    Inquisitor: "inquisitor1.jpeg",
    Chamberlain: "chamberlain1.jpeg",
    "Regent Queen": "regent-queen1.jpeg",
    "Court Whisperer": "court-whisperer1.jpeg",
    "Royal Confessor": "royal-confessor1.jpeg",
    Assassin: "assassin1.jpeg",
    Baroness: "baroness1.jpeg",
    Duke: "duke1.jpeg",
  };

  return imageMap[cardName] || "countess1.jpeg";
};

export const cards = [
  {
    id: 0,
    name: "Jester",
    strength: 0,
    countNormal: 0,
    countPremium: 1,
    effectDetails:
      "Choose another player — ideally, the one you believe is most likely to win the round. If you're correct (and your chosen player does win the round), you'll also gain a Love Token!",
    effect: "Choose a player. If they win, you gain a love token.",
  },
  {
    id: 1,
    name: "Guard",
    strength: 1,
    countNormal: 5,
    countPremium: 8,
    effectDetails:
      "Guess a strength (≠1). If correct, your target is eliminated.",
    effectDetails:
      "Choose a player and select a Strength number (other than 1). If that player has a card with that Strength, they are eliminated. On target selection, if no player can be be chosen (eg. due to Handmaid or Court Whisperer), your Guard will be discarded without effect.",
    effect: "Guess a strength (≠1). If correct, target is eliminated.",
  },
  {
    id: 2,
    name: "Priest",
    strength: 2,
    countNormal: 2,
    countPremium: 2,
    effectDetails:
      "You can look at another player’s hand (it won't be revealed to any other players).",
    effect: "Look at another player's hand.",
  },
  {
    id: 3,
    name: "Baron",
    strength: 3,
    countNormal: 2,
    countPremium: 2,
    effectDetails:
      "Choose another player, then secretly compare your second card with your target's one. The player with the lower number is knocked out of the round. In case of a tie, nothing happens.",
    effect: "Compare hands. Player with the lower card is eliminated.",
  },
  {
    id: 4,
    name: "Handmaid",
    strength: 4,
    countNormal: 2,
    countPremium: 2,
    effectDetails: "",
    effect: "You are protected until your next turn.",
  },
  {
    id: 5,
    name: "Prince",
    strength: 5,
    countNormal: 2,
    countPremium: 2,
    effectDetails: "",
    effect: "Target (or yourself) discards hand and draws a card.",
  },
  {
    id: 6,
    name: "Phantom King",
    strength: 6,
    countNormal: 1,
    countPremium: 1,
    effectDetails: "",
    effect: "You may trade hands with another player.",
  },
  {
    id: 7,
    name: "Countess",
    strength: 7,
    countNormal: 1,
    countPremium: 1,
    effectDetails: "",
    effect: "Must be played if you also have a Prince or the Phantom King.",
  },
  {
    id: 8,
    name: "Princess",
    strength: 8,
    countNormal: 1,
    countPremium: 1,
    effectDetails: "",
    effect: "If discarded (by you, or by force), you are eliminated.",
  },
  {
    id: 9,
    name: "Inquisitor",
    strength: 9,
    countNormal: 0,
    countPremium: 1,
    effectDetails: "",
    effect:
      "Guess a strength other than 1. If correct, gain an affection token.",
  },
  {
    id: 10,
    name: "Chamberlain",
    strength: 6,
    countNormal: 0,
    countPremium: 1,
    effectDetails: "",
    effect: "If eliminated, gain 1 affection token.",
  },
  {
    id: 11,
    name: "Regent Queen",
    strength: 7,
    countNormal: 0,
    countPremium: 1,
    effectDetails: "",
    effect: "Compare hands. Player with higher strength is eliminated.",
  },
  {
    id: 12,
    name: "Court Whisperer",
    strength: 4,
    countNormal: 0,
    countPremium: 2,
    effectDetails: "",
    effect: "Choose who the next player must target.",
  },
  {
    id: 13,
    name: "Royal Confessor",
    strength: 2,
    countNormal: 0,
    countPremium: 2,
    effectDetails: "",
    effect: "Trade hands. View the new card if you wish.",
  },
  {
    id: 14,
    name: "Assassin",
    strength: 0,
    countNormal: 0,
    countPremium: 1,
    effectDetails: "",
    effect: "If targeted with Guard, eliminate attacker instead.",
  },

  {
    id: 15,
    name: "Baroness",
    strength: 3,
    countNormal: 0,
    countPremium: 2,
    effectDetails: "",
    effect: "View the hands of two players.",
  },
  {
    id: 16,
    name: "Duke",
    strength: 5,
    countNormal: 0,
    countPremium: 2,
    effectDetails: "",
    effect: "If discarded or played, add +1 to your hand strength.",
  },
];
