const names = [
  { name: "Sir Lancelint", gender: "male" },
  { name: "Lady Scriptoria", gender: "female" },
  { name: "Dame JSONette", gender: "female" },
  { name: "Lord Loopalot", gender: "male" },
  { name: "Count Bracket", gender: "male" },
  { name: "Baroness Backendia", gender: "female" },
  { name: "Sir Bugslay", gender: "male" },
  { name: "Duchess Deploya", gender: "female" },
  { name: "The Null Knight", gender: "neutral" },
  { name: "Captain Callback", gender: "neutral" },
  { name: "Baroness Booleania", gender: "female" },
  { name: "Duke of Debugshire", gender: "male" },
  { name: "Dame Dotenv", gender: "female" },
  { name: "Lady Lambda", gender: "female" },
  { name: "Sir Console.log", gender: "male" },
  { name: "Countess Cloudflare", gender: "female" },
  { name: "Lord Semicolin", gender: "male" },
  { name: "Madame Mergeconflict", gender: "female" },
  { name: "The Rogue of Regex", gender: "neutral" },
  { name: "Princess Patchnote", gender: "female" },
  { name: "Sir Gitpullalot", gender: "male" },
  { name: "Monk of Markdown", gender: "neutral" },
  { name: "Viscount VanillaJS", gender: "male" },
  { name: "Lady Lintalot", gender: "female" },
  { name: "The Earl of Else", gender: "male" },
  { name: "Sir Nullpointer", gender: "male" },
  { name: "Lady Latency", gender: "female" },
  { name: "Duke of Downtime", gender: "male" },
  { name: "Lord Hotfix", gender: "male" },
  { name: "Sir Stacktrace", gender: "male" },
  { name: "Madame Middleware", gender: "female" },
  { name: "Monk of Microservices", gender: "neutral" },
  { name: "The Earl of Exceptions", gender: "male" },
  { name: "Dame Deployfail", gender: "female" },
  { name: "Count Cronjob", gender: "male" },
  { name: "Baroness Bandwidth", gender: "female" },
  { name: "Sir Unit Testington", gender: "male" },
  { name: "Lady Prototype", gender: "female" },
  { name: "Duchess Dependency", gender: "female" },
  { name: "Captain Commit", gender: "neutral" },
  { name: "Lady Pipenv", gender: "female" },
  { name: "Sir Agileton", gender: "male" },
  { name: "Madame Milestone", gender: "female" },
  { name: "Countess Callbackhell", gender: "female" },
  { name: "Sir Scrumptious", gender: "male" },
  { name: "The Vagrant of Versioning", gender: "neutral" },
  { name: "Baroness Browsercache", gender: "female" },
  { name: "Lord Jira", gender: "male" },
  { name: "The Knight of Nightly Builds", gender: "neutral" },
  { name: "Dame Dataclass", gender: "female" },
  { name: "Lord Overload", gender: "male" },
  { name: "Countess Console.error", gender: "female" },
  { name: "Sir Storypointless", gender: "male" },
  { name: "Lady Pullrequest", gender: "female" },
  { name: "Viscount VPN", gender: "male" },
  { name: "Lady ServicePortal", gender: "female" },
  { name: "The Lord of Frameworks", gender: "neutral" },
  { name: "Baroness Branchmergia", gender: "female" },
  { name: "Sir ScriptaLot", gender: "male" },
  { name: "Lady InfiniteLoopia", gender: "female" },
  { name: "Lord OutOfMemory", gender: "male" },
  { name: "Duchess Dockeria", gender: "female" },
  { name: "The Herald of HotReload", gender: "neutral" },
  { name: "Master of CodeDisaster", gender: "male" },
  { name: "Master of LockingEveryoneOut", gender: "male" },
  { name: "Lord TableQuery", gender: "male" },
  { name: "Lord of the BlueScreen of Death", gender: "male" },
  { name: "Dame Widgetonia", gender: "female" },
  { name: "The Prophet of Patchday", gender: "neutral" },
  { name: "Sir InfiniteScroll", gender: "male" },
  { name: "Lady Querystring", gender: "female" },
  { name: "Lord Outageborn", gender: "male" },
  { name: "Dame Deadlockia", gender: "female" },
  { name: "The Baron of Backups", gender: "male" },
  { name: "Countess Nullish", gender: "female" },
  { name: "Sir SyntaxError", gender: "male" },
  { name: "The Herald of Hexcodes", gender: "neutral" },
  { name: "Lord Timeout", gender: "male" },
  { name: "Captain Codefreeze", gender: "neutral" },
  { name: "The Abbot of APIs", gender: "neutral" },
  { name: "Sir FeatureCreep", gender: "male" },
  { name: "Lady Escapia", gender: "female" },
  { name: "Duchess Dropdownia", gender: "female" },
  { name: "Lord Lagomir", gender: "male" },
  { name: "The Pagefault Prophet", gender: "neutral" },
  { name: "Duchess DarkMode", gender: "female" },
  { name: "Sir SessionExpired", gender: "male" },
  { name: "Viscountess Webhookia", gender: "female" },
  { name: "Count Refactor", gender: "male" },
  { name: "Lord Legacycode", gender: "male" },
  { name: "Dame Datanode", gender: "female" },
  { name: "The Knight of Kanban", gender: "neutral" },
  { name: "Baroness Bottleneckia", gender: "female" },
  { name: "Sir SLAye", gender: "male" },
];

export function generateNickname(preferredGender = null) {
  const filtered = preferredGender
    ? names.filter(
        (n) => n.gender === preferredGender || n.gender === "neutral"
      )
    : names;
  const choice = filtered[Math.floor(Math.random() * filtered.length)];
  return choice.name;
}
